<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Клуб "Боль"</title>
</head>
<body style="background-color: black; background-size:cover; background-repeat: no-repeat" background="https://media.discordapp.net/attachments/297776073020538880/886350700186046464/rBfwIjREv7o.jpg" >
    <center><h1 style="color: white">Ты нашел секрет! А теперь уйди, вонючька.</h1></center>
</body>
</html>