<#import "parts/common.ftlh" as c>

<@c.page>
    <center><h1>БАЗА</h1></center>
    <center>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/LxWNtwoW2Yo"
                title="Rei chikita" frameborder="0" allow="accelerometer;
                autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>

    </center>
</@c.page>